on:
	push:
		branches:
			- main

concurrency: gcf-deploy

jobs:
	build-and-deploy:
		name: Cloud Functions Deploy
		runs-on: ubuntu-20.04
		strategy:
			matrix:
				functions: [Hello, Echo]
		steps:
			- uses: actions/checkout@v2
			- name: auth
				uses: google-github-actions/auth@v0.4.0
				with:
					credentials_json: ${{ secrets.GCP_CREDENTIALS }}

			- name: deploy
				uses: google-github-actions/deploy-cloud-functions@v0.10.1
				with:
					name: ${{ matrix.functions }}
					runtime: go113